assembly_info: 
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  assembly_version: "{version}"
  file: "**\\AssemblyInfo.*"
  patch: true
init:
  choco install -y rabbitmq
before_build: 
   - ps: "dnvm upgrade"
   - ps: "dnu restore"
build: 
  verbosity: minimal
test_script: 
  ps: "dnx -p test/RawRabbit.Tests test"
version: "1.9.0.{build}"
