assembly_info: 
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  assembly_version: "{version}"
  file: "**\\AssemblyInfo.*"
  patch: true
init:
  choco install -y rabbitmq
before_build: 
   - ps: "dotnet restore"
build: 
  verbosity: minimal
test_script: 
   - ps: "dotnet test .\\test\\RawRabbit.Tests"
version: "1.9.2.{build}"
